export const siteConfig = {
    name: "Fine Steel Furniture",
    description: "Premium Steel Cupboards & Storage Solutions for Vasai, Bilalpada & Beyond",
    phone: "+91 63911 55926",
    whatsappLink: "https://wa.me/916391155926",
    email: "finesteelfurniture00@gmail.com",
    address: {
        street: "Sanjay Compound, S N 118/16, Near Dube College Highway Road",
        locality: "Bilalpada, Vasai",
        region: "Maharashtra",
        postalCode: "401208",
        country: "IN",
    },
    hours: {
        weekdays: "Mon-Fri 9 AM - 6 PM",
        saturday: "Sat 9 AM - 1 PM",
        sunday: "Closed Sunday",
    },
    social: {
        facebook: "#",
        instagram: "#",
        linkedin: "#",
    },
};

export const products = [
    {
        id: "office-cupboard",
        name: "Office Cupboards",
        slug: "office-cupboards",
        category: "office",
        material: "MS",
        shortDescription: "2-door, 4-shelf MS cupboard with powder-coated finish",
        description: "Premium office cupboards designed for efficient file storage and document organization. Features durable mild steel construction with powder-coated finish for long-lasting performance.",
        applications: ["File storage", "Document organization", "Office supplies"],
        specifications: {
            dimensions: "72\" H x 36\" W x 18\" D",
            material: "Mild Steel (MS)",
            finish: "Powder Coated",
            shelves: "4 Adjustable",
            doors: "2 Hinged",
            colorOptions: ["Steel Gray", "Charcoal Black", "Ivory White"],
        },
        priceRange: "Starting from ₹12,000",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop",
        featured: true,
    },
    {
        id: "industrial-storage",
        name: "Industrial Storage Cupboards",
        slug: "industrial-storage-cupboards",
        category: "industrial",
        material: "MS",
        shortDescription: "Heavy-duty, lockable, warehouse-grade storage",
        description: "Built for demanding industrial environments. Heavy-duty construction with enhanced locking mechanisms suitable for warehouses, factories, and manufacturing facilities.",
        applications: ["Warehouse storage", "Factory equipment", "Tool organization", "Industrial supplies"],
        specifications: {
            dimensions: "84\" H x 48\" W x 24\" D",
            material: "Heavy Gauge Mild Steel",
            finish: "Industrial Powder Coat",
            shelves: "6 Heavy-duty",
            doors: "2 Reinforced",
            colorOptions: ["Industrial Gray", "Safety Yellow", "Black"],
        },
        priceRange: "Starting from ₹25,000",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop",
        featured: true,
    },
    {
        id: "ss-cabinet",
        name: "Stainless Steel Cabinets",
        slug: "stainless-steel-cabinets",
        category: "stainless",
        material: "SS304",
        shortDescription: "Food-safe, pharmaceutical-grade SS 304 construction",
        description: "Premium stainless steel cabinets ideal for pharmaceutical, food processing, and healthcare industries. Made with SS 304 grade steel for superior corrosion resistance and hygiene.",
        applications: ["Pharmaceutical storage", "Food industry", "Healthcare facilities", "Laboratories"],
        specifications: {
            dimensions: "72\" H x 36\" W x 18\" D",
            material: "Stainless Steel SS 304",
            finish: "Mirror/Matte Options",
            shelves: "4 Stainless Steel",
            doors: "2 Hinged",
            colorOptions: ["Mirror Finish", "Matte Finish", "Brushed Steel"],
        },
        priceRange: "Starting from ₹35,000",
        image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&h=400&fit=crop",
        featured: true,
    },
    {
        id: "home-storage",
        name: "Home Storage Cupboards",
        slug: "home-storage-cupboards",
        category: "home",
        material: "MS",
        shortDescription: "Sleek modern design for bedroom, kitchen, living room",
        description: "Elegant steel cupboards designed for modern homes. Perfect blend of durability and aesthetics for bedroom wardrobes, kitchen storage, and living room organization.",
        applications: ["Bedroom storage", "Kitchen cabinets", "Living room organization", "Utility storage"],
        specifications: {
            dimensions: "66\" H x 36\" W x 16\" D",
            material: "Mild Steel (MS)",
            finish: "Premium Powder Coat",
            shelves: "4 Adjustable",
            doors: "2 Soft-close",
            colorOptions: ["Pearl White", "Warm Gray", "Walnut Brown", "Midnight Blue"],
        },
        priceRange: "Starting from ₹15,000",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
        featured: false,
    },
    {
        id: "custom-cupboard",
        name: "Custom Cupboards",
        slug: "custom-cupboards",
        category: "custom",
        material: "MS/SS304",
        shortDescription: "Bespoke designs per your exact specifications",
        description: "Fully customizable cupboards tailored to your specific requirements. Choose dimensions, materials, finishes, and features to create the perfect storage solution for your space.",
        applications: ["Special dimensions", "Unique requirements", "Custom finishes", "Specialized storage"],
        specifications: {
            dimensions: "Custom",
            material: "MS or SS 304 (Your Choice)",
            finish: "Any Available Finish",
            shelves: "As Required",
            doors: "Hinged or Sliding",
            colorOptions: ["RAL Colors Available", "Custom Matching"],
        },
        priceRange: "Quote on Request",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop",
        featured: true,
    },
    {
        id: "budget-range",
        name: "Budget-Friendly Range",
        slug: "budget-friendly-range",
        category: "budget",
        material: "MS",
        shortDescription: "Affordable entry-level options, same quality",
        description: "Quality steel cupboards at affordable prices. Perfect for startups, small offices, and budget-conscious buyers. Compact sizes without compromising on durability.",
        applications: ["Startups", "Small offices", "Home office", "Budget storage"],
        specifications: {
            dimensions: "60\" H x 30\" W x 15\" D",
            material: "Mild Steel (MS)",
            finish: "Standard Powder Coat",
            shelves: "3 Fixed",
            doors: "2 Hinged",
            colorOptions: ["Gray", "White", "Black"],
        },
        priceRange: "Starting from ₹8,000",
        image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&h=400&fit=crop",
        featured: false,
    },
];

export const testimonials = [
    {
        id: 1,
        name: "Rajesh Kumar",
        role: "Office Manager",
        company: "TechStart Solutions",
        content: "Excellent quality cupboards. The durability is remarkable and delivery was right on time. We've furnished our entire office with Fine Steel products. Highly recommend their services!",
        rating: 5,
        product: "Office Cupboards",
        date: "2024-11-15",
    },
    {
        id: 2,
        name: "Priya Desai",
        role: "Startup Founder",
        company: "InnovateTech",
        content: "Best steel cupboards in Vasai. The team understood our requirements perfectly and delivered exactly what we needed. Durable, affordable, and stylish!",
        rating: 5,
        product: "Custom Cupboards",
        date: "2024-10-28",
    },
    {
        id: 3,
        name: "Sanjay Patel",
        role: "Factory Owner",
        company: "Patel Industries",
        content: "Industrial-grade quality at local prices. Our warehouse storage needs were completely met. The heavy-duty cupboards have been in use for over a year with zero issues.",
        rating: 5,
        product: "Industrial Storage Cupboards",
        date: "2024-09-12",
    },
    {
        id: 4,
        name: "Dr. Meera Shah",
        role: "Hospital Administrator",
        company: "City Medical Center",
        content: "The stainless steel cabinets are perfect for our medical storage needs. Hygienic, durable, and meet all our compliance requirements. Excellent service!",
        rating: 5,
        product: "Stainless Steel Cabinets",
        date: "2024-08-20",
    },
    {
        id: 5,
        name: "Amit Sharma",
        role: "Homeowner",
        company: "",
        content: "Beautiful home storage solutions. The cupboards blend perfectly with our modern interior. The soft-close doors are a great touch. Very satisfied with the purchase!",
        rating: 5,
        product: "Home Storage Cupboards",
        date: "2024-07-05",
    },
    {
        id: 6,
        name: "Vikram Joshi",
        role: "Restaurant Owner",
        company: "Taste of Mumbai",
        content: "Needed food-safe storage for our restaurant kitchen. Fine Steel delivered SS 304 cabinets that exceeded our expectations. Professional team and quality products.",
        rating: 5,
        product: "Stainless Steel Cabinets",
        date: "2024-06-18",
    },
];

export const blogPosts = [
    {
        id: 1,
        slug: "best-steel-cupboards-office-storage-2026",
        title: "Best Steel Cupboards for Office Storage in 2026: Complete Buyer's Guide",
        excerpt: "Discover the top steel cupboards for office storage. Learn about types, benefits, and how to choose the perfect storage solution for your workspace.",
        category: "Buyer's Guide",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-12-15",
        updatedAt: "2024-12-15",
        readTime: "8 min read",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
        featured: true,
    },
    {
        id: 2,
        slug: "mild-steel-vs-stainless-steel-cupboards",
        title: "Mild Steel vs Stainless Steel Cupboards: Which Should You Choose?",
        excerpt: "A comprehensive comparison between MS and SS cupboards. Understand durability, corrosion resistance, and best use cases for each material type.",
        category: "Buyer's Guide",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-12-10",
        updatedAt: "2024-12-10",
        readTime: "6 min read",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
        featured: true,
    },
    {
        id: 3,
        slug: "industrial-grade-steel-storage-warehouses",
        title: "Industrial-Grade Steel Storage for Warehouses & Factories",
        excerpt: "Everything you need to know about heavy-duty steel storage solutions for industrial environments. Features, durability standards, and selection tips.",
        category: "Industrial Applications",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-12-05",
        updatedAt: "2024-12-05",
        readTime: "7 min read",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 4,
        slug: "maintain-steel-cupboard-durability-guide",
        title: "How to Maintain Your Steel Cupboard: 5-Year Durability Guide",
        excerpt: "Learn essential maintenance tips to keep your steel cupboards in pristine condition. Cleaning techniques, rust prevention, and extending lifespan.",
        category: "Maintenance & Care",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-11-28",
        updatedAt: "2024-11-28",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 5,
        slug: "stainless-steel-cabinets-pharmaceutical-food",
        title: "Stainless Steel Cabinets for Pharmaceutical & Food Industries",
        excerpt: "Discover why SS 304 cabinets are essential for pharmaceutical and food industries. Standards, hygiene requirements, and application guidelines.",
        category: "Industrial Applications",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-11-20",
        updatedAt: "2024-11-20",
        readTime: "6 min read",
        image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 6,
        slug: "custom-steel-cupboards-design-solution",
        title: "Custom Steel Cupboards: Design Your Perfect Storage Solution",
        excerpt: "Everything about customizing steel cupboards for your specific needs. Process, options, lead times, and pricing information.",
        category: "Buyer's Guide",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-11-15",
        updatedAt: "2024-11-15",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&h=400&fit=crop",
        featured: true,
    },
    {
        id: 7,
        slug: "steel-furniture-trends-modern-offices-2026",
        title: "Top Steel Furniture Trends for Modern Offices in 2026",
        excerpt: "Stay ahead with the latest steel furniture design trends. Modern office aesthetics, industrial style integration, and functional designs.",
        category: "Steel Furniture Trends",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-11-10",
        updatedAt: "2024-11-10",
        readTime: "7 min read",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 8,
        slug: "vasai-virar-local-steel-furniture-manufacturers",
        title: "Why Vasai-Virar Businesses Choose Local Steel Furniture Manufacturers",
        excerpt: "Benefits of choosing local manufacturers for your steel furniture needs. Quality control, delivery advantages, and supporting local businesses.",
        category: "Local News",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-11-05",
        updatedAt: "2024-11-05",
        readTime: "4 min read",
        image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 9,
        slug: "steel-cupboard-price-guide-2026",
        title: "Steel Cupboard Price Guide: What You Should Pay in 2026",
        excerpt: "Comprehensive pricing guide for steel cupboards. Understand cost factors, price ranges by type, and how to get the best value for your investment.",
        category: "Buyer's Guide",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-10-28",
        updatedAt: "2024-10-28",
        readTime: "6 min read",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 10,
        slug: "types-steel-cupboards-every-office-needs",
        title: "5 Types of Steel Cupboards Every Office Needs",
        excerpt: "Essential guide to the five must-have steel cupboard types for any office. From file storage to personal lockers, find your perfect match.",
        category: "Office Storage Solutions",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-10-20",
        updatedAt: "2024-10-20",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 11,
        slug: "corrosion-resistant-steel-future-durable-furniture",
        title: "Corrosion-Resistant Steel: The Future of Durable Furniture",
        excerpt: "Explore the technology behind rust-proof steel furniture. Benefits, applications, and why corrosion resistance matters for long-term value.",
        category: "Steel Furniture Trends",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-10-15",
        updatedAt: "2024-10-15",
        readTime: "6 min read",
        image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=400&fit=crop",
        featured: false,
    },
    {
        id: 12,
        slug: "hinged-vs-sliding-door-cupboards",
        title: "How to Choose Between Hinged & Sliding Door Cupboards",
        excerpt: "Compare hinged and sliding door cupboards. Pros, cons, space considerations, and installation tips for making the right choice.",
        category: "Buyer's Guide",
        author: "Fine Steel Furniture Team",
        publishedAt: "2024-10-10",
        updatedAt: "2024-10-10",
        readTime: "5 min read",
        image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=400&fit=crop",
        featured: false,
    },
];

export const faqs = [
    {
        question: "What's the turnaround time for custom orders?",
        answer: "Custom orders typically take 2-3 weeks depending on complexity and current production schedule. Standard products are usually available within 5-7 business days.",
    },
    {
        question: "Do you provide installation service?",
        answer: "Yes, we offer professional installation services for all our products within Vasai-Virar and surrounding areas. Installation charges are additional and depend on location and product type.",
    },
    {
        question: "Can you ship outside Vasai-Virar?",
        answer: "Absolutely! We ship throughout Maharashtra and can arrange nationwide delivery. Shipping costs are calculated based on destination and product dimensions.",
    },
    {
        question: "What's your warranty policy?",
        answer: "All our steel cupboards come with a 2-year manufacturing warranty covering defects in material and workmanship. Extended warranty options are available.",
    },
    {
        question: "Do you offer bulk discounts?",
        answer: "Yes, we offer attractive discounts for bulk orders. Contact us with your requirements and we'll provide a customized quote with the best possible pricing.",
    },
];
